### ISSUE TITLE
Update the URL for the wiki page returned by cam-kp

### ISSUE THREAD

**Issue by karafecho** [ExposuresProvider/cam-pipeline#118]
Per discussion between Kara and Jim, this issue is to request that the URL for the wiki page returned by cam-kp is replaced with this one: https://github.com/NCATSTranslator/Translator-All/wiki/CAM-Provider-KG. This change will necessitate some changes to the code and a new deployment, but it will improve consistency, adhere to NCATS/UI specs for wiki pages, and better serve end users

**Comment by gaurav** [comment]
Ah, got it, I understand what you mean now! So instead of our current sources, which looks like this:

https://github.com/ExposuresProvider/cam-pipeline/blob/c539c7463eb8b882145e2e4725f99ee8ed6e4287/tests/test_api.py#L2433-L2444

You are proposing that we add `infores:cam-kp` as the `primary_knowledge_source` below `infores:automat-cam-kp` as the `aggregator_knowledge_source`, and then demote `infores:go-cam` to a `supporting_data_source`.

I think we can do that, but I would argue that `infores:cam-kp` should also be an `aggregator_knowledge_source` -- we don't really provide any primary knowledge, and all the information we have should be sourced to one of our primary knowledge sources (`infores:go-cam`, `infores:aop-cam` and `infores:ctd`):

https://github.com/ExposuresProvider/cam-pipeline/blob/c539c7463eb8b882145e2e4725f99ee8ed6e4287/tests/test_api.py#L101-L106

So I would propose that we change our sources so they look like this:

```json
[ 
     { 
         "resource_id": "infores:go-cam", 
         "resource_role": "primary_knowledge_source"
     }, 
     { 
         "resource_id": "infores:cam-kp", 
         "resource_role": "aggregator_knowledge_source", 
         "upstream_resource_ids": ["infores:go-cam"], 
     }, 
     { 
         "resource_id": "infores:automat-cam-kp", 
         "resource_role": "aggregator_knowledge_source", 
         "upstream_resource_ids": ["infores:cam-kp"], 
     }, 
 ] 
```

Does that make sense?

**Comment by gaurav** [comment]
@EvanDietzMorris updated Automat-CAM-KP; if you run the following query on https://automat.renci.org/#/cam-kp/reasoner_api_1_4_query_post_cam-kp_trapi:

```json
{
    "message": {
        "query_graph": {
            "nodes": {
                "n0": {
                    "ids": ["NCBIGene:15481"]
                },
                "n1": {"categories": ["biolink:AnatomicalEntity"]}
            },
            "edges": {
                "e0": {
                    "subject": "n0",
                    "object": "n1",
                    "predicates": ["biolink:active_in"]
                }
            }
        }
    }
}
```

... you get back provenance that looks like this:
```json
"390329": {
          "predicate": "biolink:active_in",
          "sources": [
            {
              "resource_id": "infores:go-cam",
              "resource_role": "primary_knowledge_source"
            },
            {
              "resource_id": "infores:cam-kp",
              "resource_role": "aggregator_knowledge_source",
              "upstream_resource_ids": [
                "infores:go-cam"
              ]
            },
            {
              "resource_id": "infores:automat-cam-kp",
              "resource_role": "aggregator_knowledge_source",
              "upstream_resource_ids": [
                "infores:cam-kp"
              ]
            }
          ],
          "subject": "NCBIGene:15481",
          "attributes": [
            {
              "attribute_type_id": "biolink:xref",
              "original_attribute_name": "xref",
              "value": [
                "http://model.geneontology.org/SYNGO_2867"
              ],
              "value_type_id": "xsd:anyURI"
            }
          ],
          "object": "UBERON:0002894"
        }
```

So `infores:go-cam` is the primary knowledge source, which is aggregated by the aggregator knowledge source `infores:cam-kp`, which is itself aggregated by the aggregator knowledge source `infores:automat-cam-kp`.

@karafecho: Is this sufficient to close this issue, at least on the Automat-CAM-KP side? We'll have to make sure that all of those inforeses point to the right URLs, but according to https://github.com/biolink/information-resource-registry/blob/e592279814e723ca16b922111037568171b87668/infores_catalog.yaml:
- `infores:automat-cam-kp` has an xref of https://github.com/NCATSTranslator/Translator-All/wiki/Automat
- `infores:cam-kp` has an xref of https://github.com/NCATSTranslator/Translator-All/wiki/CAM-Provider-KG
- `infores:go-cam` has an xref of https://github.com/NCATSTranslator/Translator-All/wiki/GO%E2%80%90CAM
- `infores:aop-cam` has an xref of https://github.com/NCATSTranslator/Translator-All/wiki/AOP-CAM
- `infores:ctd` has an xref of https://github.com/NCATSTranslator/Translator-All/wiki/CTD

So we should be good there.

**Comment by karafecho** [comment]
This all looks good to me! Sierra, Tursynay, and I just updated the infores catalog (created and merged a large PR with many changes), so your x-refs are up to date and look good to me. As such, I'll close this ticket.

**Comment by karafecho** [comment]
Oh, wait. I don't see a GO-CAM wiki page?

**Comment by gaurav** [comment]
Hmm, the correct wiki URL for GO-CAM should be https://github.com/NCATSTranslator/Translator-All/wiki/GO-CAM — I think maybe the dash got turned into an em-dash in https://github.com/biolink/information-resource-registry/blob/e592279814e723ca16b922111037568171b87668/infores_catalog.yaml. I can fix that in a bit.

**Comment by karafecho** [comment]
Yes, that is the correct xref URL for GO-CAM. I would create a PR to change the incorrect xref URL in the infores catalog.

**Comment by gaurav** [comment]
PR created! https://github.com/biolink/information-resource-registry/pull/7

We can close this ticket once that's been merged.
