### ISSUE TITLE
evaluate other triplestores

### ISSUE THREAD

**Issue by balhoff** [ExposuresProvider/cam-pipeline#18]
This is more of a project than an issue. We use Blazegraph in a lot of projects now; it has many advantages, including being free & open source, and also easy to embed. But it would be useful to know if we are missing out on any significant performance gains with any other databases.

**Comment by gaurav** [comment]
Is this a concern any more? I think we can close it since this is now Plater's problem (although we might need to work with them + ORION if some of our requests are very slow).

**Comment by balhoff** [comment]
Obsolete!
