### ISSUE TITLE
SPARQL reports are running out of memory with larger dataset

### ISSUE THREAD

**Issue by balhoff** [ExposuresProvider/cam-pipeline#73]
The queries are failing after the addition of CTD data.

**Comment by gaurav** [comment]
I think this was fixed as part of https://github.com/ExposuresProvider/cam-pipeline/pull/108?

**Comment by balhoff** [comment]
The new pipeline doesn't run SPARQL reports. If we reenable them, we should just implement them inside the datalog script.

**Comment by gaurav** [comment]
As per Jim's previous comment, this shouldn't be an issue any longer, and we can get some high-level stats from the Automat CAM-KP metadata endpoint (https://automat.renci.org/cam-kp/metadata). Closing.
