### ISSUE TITLE
Develop workflow for running build CronJob in kubernetes and deploy result

### ISSUE THREAD

**Issue by balhoff** [ExposuresProvider/cam-pipeline#75]

**Comment by balhoff** [comment]
This work should probably happen here: https://github.com/helxplatform/translator-devops/tree/develop/helm

**Comment by gaurav** [comment]
We've now got the time needed down to a sensible amount, so we can run this pretty quickly as needed. I don't think setting up a regular workflow is needed any more. @balhoff Should we close this issue, or just mark it as not urgent?

**Comment by balhoff** [comment]
I think we're fine on this now.
